<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<div class="page-header">
	<ul class="inline-ul">
		<li><a id="view_site" href="/">View Site</a></li>
		<li><a id="sign_out" href="/admin/sign/out/">Sign Out</a></li>
		<li><a id="dashboard_options">Dashboard Options</a></li>
	</ul>
</div>
<ul class="dashboard-widgets">
	
	<li class="widget-box widget-box-quarter"></li>
	<li class="widget-box widget-box-quarter"></li>
	<li class="widget-box widget-box-quarter"></li>
	<li class="widget-box widget-box-quarter"></li>
</ul>