<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<div class="page-header">
	<h2 class="page-title">Dashboard</h2>
	<a href="#dashboard_options" id="dashboard_options" name="dashboard_options">Options</a>
</div>
<ul class="dashboard-widgets">
	
	<li class="widget-box widget-box-quarter"></li>
	<li class="widget-box widget-box-quarter"></li>
	<li class="widget-box widget-box-quarter"></li>
	<li class="widget-box widget-box-quarter"></li>
</ul>