<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
$t = $this->translate;

?>
<div class="page-header">
	<ul class="inline-ul">
		<li><a id="view_site" href="/"><?php echo $t->_('View Site');?></a></li>
		<li><a id="sign_out" href="/admin/sign/out/"><?php echo $t->_('Sign Out');?></a></li>
		<li><a id="dashboard_options"><?php echo $t->_('Dashboard Options');?></a></li>
	</ul>
</div>
<ul class="dashboard-widgets">
	
	<li class="widget-box widget-box-quarter">
		
		<?php echo $this->overview();?>
	</li>
	<li class="widget-box widget-box-quarter">
	</li>
	<li class="widget-box widget-box-quarter">
	</li>
	<li class="widget-box widget-box-quarter">
	</li>
</ul>