<?php echo $this->doctype('HTML5') . "\n"; ?>
<html>
	<head>
		<?php 
			$this->headLink()->appendStylesheet( 'http://yui.yahooapis.com/3.4.1/build/cssreset/cssreset-min.css' );
			$this->headLink()->appendStylesheet( 'http://yui.yahooapis.com/3.4.1/build/cssfonts/cssfonts-min.css' );
			$this->headLink()->appendStylesheet( 'http://yui.yahooapis.com/3.4.1/build/cssgrids/grids-min.css' );
			$this->headLink()->appendStylesheet( 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/redmond/jquery-ui.css' );
			$this->headLink()->appendStylesheet( '/style/layout-content-left.css' );
			$this->headLink()->appendStylesheet( '/style/admin.css' );
			
			$this->headScript()->appendFile( 'https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js' );
			$this->headScript()->appendFile( 'https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js' );
			$this->headScript()->appendFile( 'http://view.jqueryui.com/master/ui/jquery.ui.menu.js' );
			$this->headScript()->appendFile( 'http://view.jqueryui.com/master/ui/jquery.ui.menubar.js' );
			$this->headScript()->appendFile( '/script/admin.js' );
		?>
		<?php echo $this->headMeta() . "\n"; ?>
		<?php echo $this->headTitle() . "\n"; ?>
		<?php echo $this->headScript() . "\n"; ?>
		<?php echo $this->headLink() . "\n"; ?>
		<?php echo $this->headStyle() . "\n"; ?>
	</head>
	<body class="yui3-skin-night">
		
		<div class="yui3-g" id="layout">
			<div class="yui3-u" id="nav">

				<ul id="user_menu">
					<!-- Menu items -->
					<li>
						<a href="#">Dashboard</a>
						<ul>
							<li>Test1</li>
							<li>Test2</li>
						</ul>
					</li>
				</ul>
			</div>
			<div class="yui3-u" id="main">
				<div>
					<h1 class="title"><?php $this->title;?></h1>
					
				</div>
				<?php echo $this->layout()->content; ?>
			</div>
			<div class="yui3-u" id="extra">
				
			</div>
		</div>
	</body>
	<?php if (!empty($this->message)): ?>
	<div id="message" class="ui-helper-hidden">
		<?php echo $this->message; ?>
	</div>
	<?php endif; ?>
</html>
