<?php echo $this->doctype('HTML5') . "\n";?>
<html>
	<head>
		<?php 
			$this->headLink()->appendStylesheet( '/script/yui-' . (!empty($this->yuiVersion) ? $this->yuiVersion : '3.4.1') . '/cssreset-min.css' );
			$this->headLink()->appendStylesheet( '/script/yui-' . (!empty($this->yuiVersion) ? $this->yuiVersion : '3.4.1') . '/cssfonts-min.css' );
			$this->headLink()->appendStylesheet( '/script/yui-' . (!empty($this->yuiVersion) ? $this->yuiVersion : '3.4.1') . '/grids-min.css' );
			$this->headLink()->appendStylesheet( '/script/jquery-ui-' . (!empty($this->jqueryUiVersion) ? $this->jqueryUiVersion : '1.8.16') . '/css/' . (!empty($this->theme) ? $this->theme : 'flick') . '/jquery-ui.css' );
			$this->headLink()->appendStylesheet( '/style/layout-content-left.css' );
			$this->headLink()->appendStylesheet( '/style/default.css' );
			
			$this->headScript()->appendFile( '/script/jquery-' . (!empty($this->jqueryVersion) ? $this->jqueryVersion : '1.6.2') . '/jquery-min.js' );
			$this->headScript()->appendFile( '/script/jquery-ui-' . (!empty($this->jqueryUiVersion) ? $this->jqueryUiVersion : '1.8.16') . '/jquery-ui.min.js' );
			$this->headScript()->appendFile( '/script/jquery-' . (!empty($this->jqueryVersion) ? $this->jqueryVersion : '1.6.2') . '/jquery.flyout.js' );
			$this->headScript()->appendFile( '/script/default.js' );
		?>
		<?php echo $this->headMeta() . "\n";?>
		<?php echo $this->headTitle() . "\n";?>
		<?php echo $this->headLink() . "\n";?>
		<?php echo $this->headStyle() . "\n";?>
		<?php echo $this->headScript() . "\n";?>
	</head>
	<body>
	<?php echo $this->layout()->content; ?>
	</body>
</html>
