<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<form action="/admin/json-developer-tools/application-ini" method="POST" style="height: 80%;">
	<input type="submit" value="Save" class="ui-widget ui-button" /><input class="ui-widget ui-button" type="reset" value="Unmodify" /><br />
	<textarea style="width: 89%; height: 80%;" class="ui-corner-tr ui-corner-bl"><?php echo $this->content ?></textarea>
</form>