<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
$t = $this->translate;
$title = $this->title;
$message = $this->message;

$this->title = '';
$this->message = '';
?>
<div id="dlgSignIn">
	<form action="" method="post" class="sign-in-form">
		<ul class="no-bullet-ul">
			<li><label for="username"><?php echo $t->_('User Name');?></label><input type="text" name="username" id="username" class="required" value="" /></li>
			<li><label for="password"><?php echo $t->_('Password');?></label><input type="password" name="password" id="password" class="required" value="" /></li>
			<li><input type="submit" name="submit" id="submit" value="<?php echo $t->_('Go');?>" /></li>
			<?php if (!empty($message)): ?>
			<li id="reply" class="ui-state-error ui-corner-all"> <span class="ui-icon ui-icon-alert"></span> <?php echo $message; ?> </li>
			<?php endif; ?>
		</ul>
	</form>
</div>